buildscript {
    apply from: rootProject.file('versions.gradle')

    repositories {
        mavenCentral()
        google()
        maven { url "https://jitpack.io" }
        mavenLocal()
        gradlePluginPortal()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$versions.androidgradleplugin"
        classpath "org.jetbrains.kotlin.plugin.compose:org.jetbrains.kotlin.plugin.compose.gradle.plugin:${versions.kotlin}"
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'

ext {
    PUBLISH_VERSION = rootVersionName
    ARTIFACT_ID = "konfigure-android"
}

apply from: '../common.gradle'
apply from: '../publishing.gradle'

android {
    namespace 'nz.co.trademe.konfigure.android'

    buildFeatures {
        viewBinding true // can we remove this??
        compose true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    api project(":konfigure")

    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:$versions.coroutines"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$versions.coroutines"

    implementation "androidx.appcompat:appcompat:$versions.appcompat"
    implementation "com.google.android.material:material:$versions.material"
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation "androidx.lifecycle:lifecycle-extensions:2.2.0"

    // Jetpack Compose Dependencies
    implementation(platform("androidx.compose:compose-bom:$versions.composeBom"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-graphics")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.activity:activity-compose")
    // Tooling for previews in Android Studio
    debugImplementation("androidx.compose.ui:ui-tooling")
    implementation("androidx.compose.ui:ui-tooling-preview")
}
